-- NEUTRALIZADA — Fase de saneamiento de startup SEGOLIFE (ver CLAUDE.md).
--
-- Esta migración creaba/actualizaba en cualquier base de datos donde se
-- aplicara un usuario admin real con el email de un tercero ajeno a este
-- proyecto (reservas@nayadeexperiences.es), una contraseña temporal
-- documentada en texto plano en este mismo archivo, y le concedía TODOS
-- los permisos RBAC vía CROSS JOIN. Esto es exactamente el patrón de
-- "garantizar privilegios de administrador para reservas@nayadeexperiences.es"
-- que esta fase de saneamiento debía eliminar: nunca debe ejecutarse contra
-- una base de datos de Segolife.
--
-- No se ha borrado el archivo (rompería la numeración secuencial de
-- migraciones) ni se ha aplicado nunca contra ningún entorno real — las
-- tablas RBAC estaban vacías en todos los entornos conocidos antes de esta
-- fase, así que no hay ningún checksum de migración que preservar.
--
-- El mecanismo correcto y ya existente para dar de alta un administrador de
-- Segolife es `node scripts/create-admin.mjs` (explícito, con credenciales
-- propias de quien lo ejecuta), documentado en CLAUDE.md.
SELECT 1;
