CREATE TABLE `benefit_definitions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `name` varchar(256) NOT NULL,
  `slug` varchar(128) NOT NULL,
  `description` text,
  `benefit_type` enum('free_entry','free_product','discount_percentage','discount_fixed','vip_access','priority_access','upgrade','custom') NOT NULL,
  `destination_venue_id` int,
  `destination_event_id` int,
  `product_id` int,
  `discount_type` enum('percentage','fixed'),
  `discount_value` int,
  `value_metadata` json,
  `active` boolean NOT NULL DEFAULT true,
  `image_url` varchar(512),
  `name_en` varchar(256),
  `name_es` varchar(256),
  `description_en` text,
  `description_es` text,
  `terms_en` text,
  `terms_es` text,
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `benefit_definitions_id` PRIMARY KEY(`id`),
  CONSTRAINT `benefit_definitions_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `benefit_communities` (
  `id` int AUTO_INCREMENT NOT NULL,
  `benefit_definition_id` int NOT NULL,
  `community_id` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `benefit_communities_id` PRIMARY KEY(`id`),
  CONSTRAINT `benefit_communities_unique` UNIQUE(`benefit_definition_id`,`community_id`)
);
--> statement-breakpoint
CREATE TABLE `benefit_rules` (
  `id` int AUTO_INCREMENT NOT NULL,
  `name` varchar(256) NOT NULL,
  `description` text,
  `source_type` enum('consumption','consumption_product','venue_visit','event_attendance','token_earning','recurrence','campaign','manual','ticket','future_external') NOT NULL,
  `source_venue_id` int,
  `source_event_id` int,
  `source_product_id` int,
  `community_id` int,
  `min_amount_cents` int,
  `min_visits` int,
  `recurrence_window` enum('day','week','month'),
  `condition_days_of_week` json,
  `condition_start_time` varchar(5),
  `condition_end_time` varchar(5),
  `starts_at` timestamp,
  `ends_at` timestamp,
  `active` boolean NOT NULL DEFAULT true,
  `priority` int NOT NULL DEFAULT 0,
  `benefit_definition_id` int NOT NULL,
  `quantity` int NOT NULL DEFAULT 1,
  `validity_type` enum('immediate','offset','day_anchored') NOT NULL DEFAULT 'immediate',
  `validity_offset_minutes` int,
  `validity_duration_minutes` int,
  `validity_start_time` varchar(5),
  `validity_end_time` varchar(5),
  `validity_days_offset` int,
  `max_per_user` int,
  `max_per_day` int,
  `max_total` int,
  `once_per_origin` boolean NOT NULL DEFAULT false,
  `once_per_rule` boolean NOT NULL DEFAULT false,
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `benefit_rules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_benefits` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `benefit_definition_id` int NOT NULL,
  `benefit_rule_id` int,
  `source_type` varchar(64) NOT NULL,
  `source_id` int,
  `source_venue_id` int,
  `source_event_id` int,
  `source_ledger_id` int,
  `community_id` int,
  `status` enum('active','used','expired','cancelled') NOT NULL DEFAULT 'active',
  `granted_at` timestamp NOT NULL DEFAULT (now()),
  `valid_from` timestamp NOT NULL,
  `valid_until` timestamp,
  `used_at` timestamp,
  `used_at_venue_id` int,
  `used_at_event_id` int,
  `used_by_staff_user_id` int,
  `qr_token` varchar(64),
  `qr_token_hash` varchar(64),
  `idempotency_key` varchar(191),
  `metadata` json,
  `granted_by_user_id` int,
  `cancelled_at` timestamp,
  `cancelled_by_user_id` int,
  `cancellation_reason` varchar(256),
  `created_at` timestamp NOT NULL DEFAULT (now()),
  `updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `user_benefits_id` PRIMARY KEY(`id`),
  CONSTRAINT `user_benefits_idempotency_key_unique` UNIQUE(`idempotency_key`),
  CONSTRAINT `user_benefits_qr_token_hash_unique` UNIQUE(`qr_token_hash`)
);
--> statement-breakpoint
CREATE TABLE `benefit_redemption_attempts` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_benefit_id` int,
  `token_fingerprint` varchar(64),
  `staff_user_id` int,
  `venue_id` int,
  `result` enum('valid','already_used','expired','not_active_yet','cancelled','wrong_venue','wrong_event','unauthorized_staff','invalid_token','not_found','rate_limited','error') NOT NULL,
  `ip_address` varchar(64),
  `user_agent` varchar(256),
  `created_at` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `benefit_redemption_attempts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `venue_staff` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `venue_id` int NOT NULL,
  `active` boolean NOT NULL DEFAULT true,
  `created_at` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `venue_staff_id` PRIMARY KEY(`id`),
  CONSTRAINT `venue_staff_unique` UNIQUE(`user_id`,`venue_id`)
);
